spring.application.name=SpendTrack

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.dpyabmuvawukytxgdnjs&password=Crimsonrubyheartjade95
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.dpyabmuvawukytxgdnjs
spring.datasource.password=Crimsonrubyheartjade95

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
